# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      24.1.0-319.113
# Date created:         Thu Mar 21 11:26:13 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Workflow_Delete Application in ArgoCD.yaml
  - Workflow_Install Argo Rollouts.yaml
  - Workflow_Install ArgoCD.yaml
  - Workflow_Setup ArgoCD application with initial deployment.yaml
  - Workflow_Update Application in ArgoCD.yaml
